version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: isaac
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: